"""Export a session summary as a PDF study guide or Markdown."""
import io
from datetime import date


async def export_as_markdown(teacher_name: str, level: str, session_id, summary: dict) -> str:
    lines = [
        "---",
        f"teacher: {teacher_name}",
        f"date: {date.today().isoformat()}",
        f"level: {level}",
        f"session_id: {session_id}",
        "---",
        "",
        f"# Session Notes",
        "",
        "## Overview",
        summary.get("overview", ""),
        "",
        "## Key Concepts",
        *[f"- {c}" for c in summary.get("key_concepts", [])],
        "",
        "## Definitions",
        *[f"- **{d['term']}** — {d['definition']}" for d in summary.get("definitions", [])],
        "",
        "## Key Takeaways",
        *[f"{i}. {t}" for i, t in enumerate(summary.get("takeaways", []), 1)],
        "",
        "## Questions to Explore",
        *[f"- {q}" for q in summary.get("questions_to_explore", [])],
        "",
        "## Topics to Review",
        *[f"- {t}" for t in summary.get("topics_to_review", [])],
    ]
    return "\n".join(lines)


async def export_as_pdf(teacher_name: str, level: str, session_id, summary: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="TeachClone Session Notes")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("TeachClone — Session Notes", styles["Title"]),
        Paragraph(f"{teacher_name} · {level} · {date.today().isoformat()}", styles["Normal"]),
        Spacer(1, 16),
        Paragraph("Overview", styles["Heading2"]),
        Paragraph(summary.get("overview", ""), styles["Normal"]),
        Spacer(1, 10),
        Paragraph("Key Concepts", styles["Heading2"]),
        ListFlowable(
            [ListItem(Paragraph(c, styles["Normal"])) for c in summary.get("key_concepts", [])],
            bulletType="bullet",
        ),
        Spacer(1, 10),
        Paragraph("Definitions", styles["Heading2"]),
        ListFlowable(
            [
                ListItem(Paragraph(f"<b>{d['term']}</b> — {d['definition']}", styles["Normal"]))
                for d in summary.get("definitions", [])
            ],
            bulletType="bullet",
        ),
        Spacer(1, 10),
        Paragraph("Key Takeaways", styles["Heading2"]),
        ListFlowable(
            [ListItem(Paragraph(t, styles["Normal"])) for t in summary.get("takeaways", [])],
            bulletType="1",
        ),
        Spacer(1, 10),
        Paragraph("Topics to Review", styles["Heading2"]),
        ListFlowable(
            [ListItem(Paragraph(t, styles["Normal"])) for t in summary.get("topics_to_review", [])],
            bulletType="bullet",
        ),
        Spacer(1, 16),
        Paragraph(f"Generated by TeachClone · session {session_id}", styles["Italic"]),
    ]
    doc.build(story)
    return buf.getvalue()
