export const curriculumStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: 'var(--bg-primary)',
    overflow: 'hidden',
  },
  header: {
    padding: '20px 24px 16px 24px',
    borderBottom: '1px solid var(--border-subtle)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'var(--bg-secondary)',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--text-primary)',
  },
  subtitle: {
    margin: '4px 0 0 0',
    fontSize: '13px',
    color: 'var(--text-secondary)',
  },
  progressBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--bg-tertiary)',
    border: '1px solid var(--border-color)',
    padding: '6px 14px',
    borderRadius: '20px',
    fontSize: '12px',
  },
  progressLabel: {
    color: 'var(--text-muted)',
  },
  progressValue: {
    color: 'var(--text-accent)',
    fontFamily: 'var(--font-mono)',
    fontWeight: '600',
  },
  searchBarRow: {
    padding: '12px 24px',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-primary)',
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    padding: '8px 14px',
    maxWidth: '500px',
  },
  searchInput: {
    background: 'none',
    border: 'none',
    outline: 'none',
    color: 'var(--text-primary)',
    fontSize: '13px',
    fontFamily: 'var(--font-sans)',
    width: '100%',
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 24px',
  },
  centerBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    gap: '12px',
  },
  loadingText: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
  },
  emptyCard: {
    maxWidth: '460px',
    margin: '60px auto',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-lg)',
    padding: '40px 32px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  emptyIcon: {
    fontSize: '44px',
    marginBottom: '12px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: 'var(--text-primary)',
    margin: '0 0 8px 0',
  },
  emptyText: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    lineHeight: '1.5',
    margin: '0 0 20px 0',
  },
  generateBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--accent-primary)',
    color: '#ffffff',
    border: 'none',
    borderRadius: 'var(--radius-md)',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  errorText: {
    marginTop: '12px',
    fontSize: '12px',
    color: 'var(--red)',
  },
  chapterList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    maxWidth: '860px',
    margin: '0 auto',
  },
  chapterCard: {
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    overflow: 'hidden',
    transition: 'border-color 0.15s ease',
  },
  chapterHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    cursor: 'pointer',
    userSelect: 'none',
    backgroundColor: 'var(--bg-secondary)',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flex: 1,
    overflow: 'hidden',
  },
  checkboxBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
  },
  chapterInfo: {
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  chapterNumber: {
    fontSize: '11px',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    color: 'var(--accent-primary)',
  },
  chapterTitle: {
    margin: '2px 0 0 0',
    fontSize: '14px',
    fontWeight: '600',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginLeft: '12px',
  },
  durationChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
  },
  startLearningBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--bg-tertiary)',
    color: 'var(--text-accent)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-sm)',
    padding: '5px 10px',
    fontSize: '12px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  expandIcon: {
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
  },
  chapterBody: {
    padding: '14px 20px 18px 50px',
    borderTop: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-tertiary)',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  chapterDesc: {
    margin: 0,
    fontSize: '13px',
    color: 'var(--text-secondary)',
    lineHeight: '1.5',
  },
  subSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  subSectionTitle: {
    fontSize: '11px',
    fontWeight: '700',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
  },
  topicPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  topicPill: {
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '3px 10px',
    fontSize: '12px',
    color: 'var(--text-primary)',
  },
  conceptChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  conceptChip: {
    fontSize: '12px',
    color: 'var(--text-accent)',
    backgroundColor: 'var(--accent-glow)',
    padding: '3px 8px',
    borderRadius: '6px',
  },
};
