from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, ForeignKey, Integer, String, Text
from sqlalchemy import JSON
from app.db.types import GUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base
from app.models._base import PkMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models.media_source import MediaSource
    from app.models.organization import Organization
    from app.models.student_session import StudentSession
    from app.models.user import User


class TeacherProfile(Base, PkMixin, TimestampMixin):
    __tablename__ = "teacher_profiles"

    # Ownership (a profile belongs to a user, or is org-shared).
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("users.id"), nullable=True, index=True
    )
    org_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("organizations.id"), nullable=True, index=True
    )

    name: Mapped[str] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    tts_voice: Mapped[str] = mapped_column(String, default="nova")

    # Extracted teaching style (StyleProfile / DNA report JSON).
    style_profile: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Ultra-detailed system prompt generated by the DNA pipeline. When set,
    # prompt_builder uses it as the persona base (new DNA teachers); when null,
    # it falls back to the legacy style-composed prompt (old teachers).
    system_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    total_sources: Mapped[int] = mapped_column(Integer, default=0)

    # --- Discovery + sharing ------------------------------------------------
    # private  = only owner/org can use
    # unlisted = anyone with the share link can use
    # public   = listed in the "popular teachers" directory
    visibility: Mapped[str] = mapped_column(String, default="private", index=True)
    share_token: Mapped[str | None] = mapped_column(
        String, unique=True, nullable=True, index=True
    )
    share_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    share_mode: Mapped[str] = mapped_column(String, default="clone")  # clone|view
    forked_from_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("teacher_profiles.id"), nullable=True
    )

    # Popularity metrics power the "most used teacher" ranking.
    session_count: Mapped[int] = mapped_column(Integer, default=0)
    unique_learners: Mapped[int] = mapped_column(Integer, default=0)

    user: Mapped["User | None"] = relationship(
        back_populates="teacher_profiles", foreign_keys=[user_id]
    )
    organization: Mapped["Organization | None"] = relationship(
        back_populates="teacher_profiles"
    )
    media_sources: Mapped[list["MediaSource"]] = relationship(
        back_populates="teacher_profile", cascade="all, delete-orphan"
    )
    sessions: Mapped[list["StudentSession"]] = relationship(
        back_populates="teacher_profile"
    )
