export const chatStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: 'var(--bg-primary)',
    overflow: 'hidden',
  },
  errorBanner: {
    backgroundColor: 'rgba(248, 81, 73, 0.1)',
    borderBottom: '1px solid rgba(248, 81, 73, 0.3)',
    color: 'var(--red)',
    fontSize: '12px',
    padding: '8px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  thread: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    maxWidth: 'var(--chat-max-width)',
    width: '100%',
    margin: '0 auto',
  },
  emptyState: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '40px 20px',
    color: 'var(--text-secondary)',
    margin: 'auto 0',
  },
  emptyAvatar: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-secondary)',
    border: '2px solid var(--accent-glow)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
    boxShadow: '0 0 20px var(--accent-glow)',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: 'var(--text-primary)',
    margin: '0 0 8px 0',
  },
  emptySubtitle: {
    fontSize: '14px',
    color: 'var(--text-muted)',
    maxWidth: '440px',
    lineHeight: '1.5',
    margin: 0,
  },
  skeletonRow: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    justifyContent: 'flex-start',
  },
  skeletonAvatar: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '15px',
    flexShrink: 0,
  },
  skeletonBubble: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 16px',
    backgroundColor: 'var(--bg-tertiary)',
    borderRadius: 'var(--radius-md)',
    borderTopLeftRadius: '2px',
  },
  thinkingText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
};
