export const graphStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: 'var(--bg-primary)',
    overflow: 'hidden',
  },
  controlsBar: {
    height: '48px',
    backgroundColor: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    zIndex: 5,
  },
  controlsLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  graphTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: 'var(--text-primary)',
  },
  metaBadge: {
    fontSize: '11px',
    fontFamily: 'var(--font-mono)',
    backgroundColor: 'var(--bg-tertiary)',
    border: '1px solid var(--border-color)',
    padding: '2px 8px',
    borderRadius: '12px',
    color: 'var(--text-secondary)',
  },
  controlsRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  toolBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-secondary)',
    padding: '4px 10px',
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  buildBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--accent-primary)',
    color: '#ffffff',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  viewport: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
  },
  iframeWrapper: {
    width: '100%',
    height: '100%',
    transition: 'transform 0.15s ease-out',
  },
  iframe: {
    width: '100%',
    height: '100%',
    border: 'none',
    backgroundColor: '#0d1117',
  },
  skeletonContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    padding: '40px',
  },
  skeletonPulse: {
    width: '240px',
    height: '240px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, var(--accent-glow) 0%, rgba(33, 38, 45, 0.4) 70%)',
    animation: 'pulse 2s infinite ease-in-out',
  },
  skeletonText: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
  },
  emptyContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '40px 20px',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '12px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: 'var(--text-primary)',
    margin: '0 0 6px 0',
  },
  emptySubtitle: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    maxWidth: '400px',
    margin: '0 0 20px 0',
    lineHeight: '1.5',
  },
  primaryBuildBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--accent-primary)',
    color: '#ffffff',
    border: 'none',
    borderRadius: 'var(--radius-md)',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
  },
  errorText: {
    marginTop: '12px',
    fontSize: '12px',
    color: 'var(--red)',
  },
  nodeListFallback: {
    padding: '24px',
    overflowY: 'auto',
    height: '100%',
  },
  nodesPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginTop: '12px',
  },
  conceptPill: {
    background: 'var(--bg-secondary)',
    color: 'var(--text-primary)',
    border: '1px solid',
    borderRadius: '16px',
    padding: '6px 14px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  conceptPanel: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    width: '320px',
    maxHeight: 'calc(100% - 32px)',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    zIndex: 10,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid var(--border-color)',
  },
  panelTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  panelTitle: {
    margin: 0,
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--text-primary)',
  },
  closePanelBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '2px',
  },
  panelBody: {
    padding: '16px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    fontSize: '13px',
  },
  detailSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sectionLabel: {
    fontSize: '11px',
    fontWeight: '700',
    textTransform: 'uppercase',
    color: 'var(--text-secondary)',
  },
  conceptList: {
    margin: 0,
    paddingLeft: '20px',
    color: 'var(--text-primary)',
  },
  subtleText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
  neighborsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    fontSize: '12px',
  },
  neighborItem: {
    color: 'var(--text-secondary)',
  },
};
